# Generated by Django 6.0.7 on 2026-07-24 17:35

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('public_key', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('type_of_user', models.CharField(choices=[('Student', 'Student'), ('Organization', 'Organization')], default='Student', max_length=50)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('outcomes', models.TextField()),
                ('is_complete', models.BooleanField(default=False)),
                ('companies_interested', models.ManyToManyField(blank=True, related_name='interested_courses', to=settings.AUTH_USER_MODEL)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='courses_in_progress',
            field=models.ManyToManyField(blank=True, related_name='users_in_progress', to='core.course'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_section', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('Info_panel', 'Information Panel'), ('Coding_problem', 'Coding Problem'), ('Video', 'Video'), ('Blank', 'Blank')], default='MCQ', max_length=50)),
                ('module_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.module')),
            ],
            options={
                'order_with_respect_to': 'module_id',
            },
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('mcq_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=200)),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='core.section')),
            ],
        ),
        migrations.CreateModel(
            name='Info_panel',
            fields=[
                ('info_panel_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_panels', to='core.section')),
            ],
        ),
        migrations.CreateModel(
            name='Coding_problem',
            fields=[
                ('coding_problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('test_cases', models.JSONField()),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coding_problems', to='core.section')),
            ],
        ),
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('blank_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('answers', models.TextField()),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blanks', to='core.section')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.section')),
            ],
        ),
    ]
