# Generated by Django 6.0.7 on 2026-07-24 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('outcomes', models.TextField()),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_section', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('Info_panel', 'Information Panel'), ('Coding_problem', 'Coding Problem'), ('Video', 'Video'), ('Blank', 'Blank')], default='MCQ', max_length=50)),
                ('module_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.module')),
            ],
            options={
                'order_with_respect_to': 'module_id',
            },
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('mcq_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=200)),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='core.section')),
            ],
        ),
        migrations.CreateModel(
            name='Info_panel',
            fields=[
                ('info_panel_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_panels', to='core.section')),
            ],
        ),
        migrations.CreateModel(
            name='Coding_problem',
            fields=[
                ('coding_problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('test_cases', models.JSONField()),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coding_problems', to='core.section')),
            ],
        ),
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('blank_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('answers', models.TextField()),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blanks', to='core.section')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('public_key', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('type_of_user', models.CharField(choices=[('Student', 'Student'), ('Organization', 'Organization')], default='Student', max_length=50)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('courses_in_progress', models.ManyToManyField(blank=True, related_name='users_in_progress', to='core.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='companies_interested',
            field=models.ManyToManyField(blank=True, related_name='interested_courses', to='core.user'),
        ),
        migrations.AddField(
            model_name='course',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to='core.user'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.section')),
            ],
        ),
    ]
