# Generated by Django 6.0.7 on 2026-07-24 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_correct', models.IntegerField(choices=[(0, 'Incorrect'), (1, 'Correct')], default=0)),
                ('user_answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.section')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.user')),
            ],
            options={
                'unique_together': {('user_id', 'section_id')},
            },
        ),
    ]
